/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.controller_absensi;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author WIN 7
 */
public class frm_absen extends javax.swing.JFrame {

    /**
     * Creates new form frm_absen
     */
    private controller.controller_absensi absensiService;
    
    public frm_absen() {
        initComponents();
        this.absensiService = new controller.controller_absensi();
        this.awal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_nik = new javax.swing.JTextField();
        btn_cari = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_nama = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_jabatan = new javax.swing.JLabel();
        btn_absen_keluar = new javax.swing.JButton();
        btn_absen_masuk = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        dtp_tgl = new com.toedter.calendar.JDateChooser();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("NIK");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 20));
        getContentPane().add(txt_nik, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 203, -1));

        btn_cari.setText("Cari");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 90, -1));

        jLabel2.setText("Tanggal & Waktu");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, 20));

        jLabel3.setText("Nama : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        lbl_nama.setText("-");
        getContentPane().add(lbl_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        jLabel5.setText("Jabatan");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        lbl_jabatan.setText("-");
        getContentPane().add(lbl_jabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        btn_absen_keluar.setText("Absen Keluar");
        btn_absen_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_absen_keluarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_absen_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        btn_absen_masuk.setText("Absen Masuk");
        btn_absen_masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_absen_masukActionPerformed(evt);
            }
        });
        getContentPane().add(btn_absen_masuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Tanggal", "NIK", "Nama", "Jabatan", "Masuk", "Keluar"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 620, 190));

        dtp_tgl.setDateFormatString("dd/MM/yyyy HH:mm:ss");
        getContentPane().add(dtp_tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 190, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void awal()
    {
        dtp_tgl.setDate(new Date());
        
        try
        {
            List<model.table_absen> data = absensiService.tampil();
            DefaultTableModel table = (DefaultTableModel) jTable1.getModel();
            table.setRowCount(0);
            for (model.table_absen row : data)
            {
                String keluar = "";
                if (!row.getKeluar().equals(row.getMasuk()))
                {
                    keluar = new SimpleDateFormat("HH:mm:ss").format(row.getKeluar());
                }
                table.addRow(new Object[] { new SimpleDateFormat("dd/MM/yyyy").format(row.getTanggal()), row.getNIK(), row.getNama(), row.getJabatan(), new SimpleDateFormat("HH:mm:ss").format(row.getMasuk()), keluar });
            }
            jTable1.setModel(table);
        }
        catch (SQLException ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    
    private void btn_absen_masukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_absen_masukActionPerformed
        model.model_absensi absen = new model.model_absensi();
        absen.setNIK(txt_nik.getText());
        absen.setTanggal(dtp_tgl.getDate());
        absen.setMasuk(dtp_tgl.getDate());
        try
        {
            absensiService.masuk(absen);
            this.awal();
            JOptionPane.showMessageDialog(null, "Anda berhasil melakukan absensi masuk");
        }
        catch (SQLException ex)
        {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btn_absen_masukActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        try
        {
            String[] karyawan = absensiService.getKaryawan(txt_nik.getText());
            if (karyawan[0] == null)
            {
                JOptionPane.showMessageDialog(null, "Data karyawan tidak ditemukan");
            }
            else
            {
                lbl_nama.setText(karyawan[1]);
                lbl_jabatan.setText(karyawan[2]);
            }
        }
        catch (SQLException ex)
        {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btn_cariActionPerformed

    private void btn_absen_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_absen_keluarActionPerformed
        model.model_absensi absen = new model.model_absensi();
        absen.setNIK(txt_nik.getText());
        absen.setKeluar(dtp_tgl.getDate());
        try
        {
            absensiService.keluar(absen);
            this.awal();
            JOptionPane.showMessageDialog(null, "Anda berhasil melakukan absensi keluar");
        }
        catch (SQLException ex)
        {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btn_absen_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_absen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_absen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_absen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_absen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_absen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_absen_keluar;
    private javax.swing.JButton btn_absen_masuk;
    private javax.swing.JButton btn_cari;
    private com.toedter.calendar.JDateChooser dtp_tgl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_jabatan;
    private javax.swing.JLabel lbl_nama;
    private javax.swing.JTextField txt_nik;
    // End of variables declaration//GEN-END:variables
}
