/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.controller_gaji;
import controller.controller_karyawan;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author WIN 7
 */
public class frm_gaji extends javax.swing.JFrame {

    /**
     * Creates new form frm_gaji
     */
    public frm_gaji() {
        initComponents();
        gajiService = new controller_gaji();
        controller.controller_karyawan karyawanService = new controller_karyawan();
        this.awal();
        try
        {
            cbo_nik.removeAllItems();
            List<model.model_karyawan> karyawan = karyawanService.tampil();
            for (model.model_karyawan row : karyawan)
            {
                cbo_nik.addItem(row.getNIK());
            }
        }
        catch (SQLException e)
        {
            System.out.println(e.getMessage());
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_no_slip = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbo_nik = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        txt_jabatan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_gaji_pokok = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_tunjangan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_total_gaji = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txt_jumlah_kehadiran = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("No Slip");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));
        jPanel1.add(txt_no_slip, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 210, -1));

        jLabel2.setText("Nik");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        cbo_nik.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbo_nik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_nikActionPerformed(evt);
            }
        });
        jPanel1.add(cbo_nik, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 210, -1));

        jLabel3.setText("Nama");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel4.setText("Jabatan");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        jPanel1.add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 210, -1));
        jPanel1.add(txt_jabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 210, -1));

        jLabel5.setText("Gaji Pokok");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));
        jPanel1.add(txt_gaji_pokok, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 210, -1));

        jLabel6.setText("Tunjangan");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 20));
        jPanel1.add(txt_tunjangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 210, -1));

        jLabel7.setText("Total Gaji");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, 20));
        jPanel1.add(txt_total_gaji, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 210, -1));

        btn_simpan.setIcon(new javax.swing.ImageIcon("D:\\KUMPULAN TUGAS KULIAH\\TUGAS KULIAH SEMESTER 3\\Pemrograman Berbasis Objek\\gambar pbo\\SAVE.png")); // NOI18N
        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon("D:\\KUMPULAN TUGAS KULIAH\\TUGAS KULIAH SEMESTER 3\\Pemrograman Berbasis Objek\\gambar pbo\\logout.png")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 120, 60));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No Slip", "NIK", "Nama", "Jabatan", "Gaji Pokok", "Tunjangan", "Jumlah Kehadiran", "Total gaji"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 620, 100));

        jLabel8.setText("Jumlah Kehadiran ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));
        jPanel1.add(txt_jumlah_kehadiran, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 210, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void awal()
    {
        try {
            List<model.table_gaji> data = gajiService.tampil();
            DefaultTableModel table = (DefaultTableModel) jTable1.getModel();
            table.setRowCount(0);
            for (model.table_gaji row : data)
            {
                table.addRow(new Object[] { row.getNo_slip(), row.getNIK(), row.getNama(), row.getJabatan(), row.getGaji_pokok(), row.getTunjangan(), row.getJumlah_kehadiran(), row.getTotal_gaji()});
            }
            jTable1.setModel(table);
        } catch (SQLException ex) {
            Logger.getLogger(frm_gaji.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    private controller.controller_gaji gajiService;
    
    private void cbo_nikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_nikActionPerformed
        try {
            Object item = cbo_nik.getSelectedItem();
            if (item != null)
            {   
                String[] karyawan = gajiService.getKaryawan(cbo_nik.getSelectedItem().toString());
                txt_nama.setText(karyawan[0]);
                txt_jabatan.setText(karyawan[1]);
                txt_gaji_pokok.setText(karyawan[2]);
                txt_tunjangan.setText(karyawan[3]);
                txt_jumlah_kehadiran.setText(karyawan[4]);
                int total = Integer.parseInt(karyawan[2]) + (Integer.parseInt(karyawan[3]) * Integer.parseInt(karyawan[4]));
                txt_total_gaji.setText(Integer.toString(total));
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_cbo_nikActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        model.model_gaji gaji = new model.model_gaji();
        gaji.setNo_slip(Integer.parseInt(txt_no_slip.getText()));
        gaji.setNIK(cbo_nik.getSelectedItem().toString());
        gaji.setGaji_pokok(Integer.parseInt(txt_gaji_pokok.getText()));
        gaji.setJumlah_kehadiran(Integer.parseInt(txt_jumlah_kehadiran.getText()));
        gaji.setTotal_gaji(Integer.parseInt(txt_total_gaji.getText()));
        gaji.setTunjangan(Integer.parseInt(txt_tunjangan.getText()));
        try {
            gajiService.simpan(gaji);
            this.awal();
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_gaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_gaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_gaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_gaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_gaji().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_simpan;
    private javax.swing.JComboBox cbo_nik;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_gaji_pokok;
    private javax.swing.JTextField txt_jabatan;
    private javax.swing.JTextField txt_jumlah_kehadiran;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_no_slip;
    private javax.swing.JTextField txt_total_gaji;
    private javax.swing.JTextField txt_tunjangan;
    // End of variables declaration//GEN-END:variables
}
