/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import controller.controller_jabatan;
import controller.controller_karyawan;
import controller.interface_karyawan;
import java.util.ArrayList;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import model.model_karyawan;


/**
 *
 * @author WIN 7
 */
public class frm_karyawan extends javax.swing.JFrame {
    
    List<model.model_karyawan> recordkaryawan=new ArrayList<>();
      interface_karyawan kryservice;
    
    void panggildata(){
        try{
           recordkaryawan = kryservice.tampil();
        } catch(SQLException e){
            System.out.println("Terjadi kesalahan pada : "+ e);
        }
    }
    
    void isitabel(){
        Object data[][] = new Object[recordkaryawan.size()][10];
        int x = 0;
        for (model.model_karyawan kry : recordkaryawan){
            data[x][0] = kry.getNIK();
            data[x][1] = kry.getNama();
            data[x][2] = kry.getAlamat();
            data[x][3] = kry.getTempat_lahir();
            data[x][4] = kry.getTgl_lahir();
            data[x][5] = kry.getKodeJabatan();
            data[x][6] = kry.getJenis_kelamin();
            data[x][7] = kry.getAlamat();
            data[x][8] = kry.getStatus();
            x++;
        }
        //membuat nama kolom di tabel
        String kolom[] = {"NIK","Nama","Alamat","Tempat Lahir","Tanggal Lahir","Kode Jabatan","Jenis Kelamin","Alamat","Status"};
        tbl_karyawan.setModel(new DefaultTableModel(data,kolom)
        {  
            //membuat tabel tidak bisa diedit saat diklik    
            @Override  
            public boolean isCellEditable(int rowIndex, int colIndex) {  
                return false;  
            }
        });
    }
    void refreshdata(){
        controller_jabatan jabatan = new controller_jabatan();
        try
        {
            List<model.model_jabatan> model_jabatan = jabatan.tampil();
            cbo_kd_jabatan.removeAllItems();
            for (model.model_jabatan row : model_jabatan)
            {
                cbo_kd_jabatan.addItem(row.getKode_jabatan());
            }
        }
        catch (SQLException ex)
        {
            System.out.printf(ex.getMessage());
        }
        
        panggildata();
        isitabel();
        bersih();
    }
    
    void bersih()
    {
        txt_nik.requestFocus();
        txt_nama.setText("");
        txt_tempatlahir.setText("");
        txt_tanggallahir.setText("");
        txt_jeniskelamin.setText("");
        txt_alamat.setText("");
        txt_status.setText("");
        cbo_kd_jabatan.setName("");
        
        
        
    }
    
    
    /**
     * Creates new form frm_karyawan
     */
    public frm_karyawan() {
        initComponents();
        setLocationRelativeTo(null);
        
        kryservice = new controller_karyawan();
        controller.controller_jabatan jabatanservice = new controller_jabatan();
        try
        {
            List<model.model_jabatan> jabatan = jabatanservice.tampil();
            for (model.model_jabatan row : jabatan)
            {
                cbo_kd_jabatan.addItem(row.getKode_jabatan());
            }
        }
        catch (SQLException e)
        {
            
        }
        

        this.refreshdata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_nik = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        txt_tempatlahir = new javax.swing.JTextField();
        txt_tanggallahir = new javax.swing.JTextField();
        txt_jeniskelamin = new javax.swing.JTextField();
        txt_alamat = new javax.swing.JTextField();
        txt_status = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        cbo_kd_jabatan = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        btn_simpan = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_karyawan = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("NIK");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 22, -1, -1));

        jLabel4.setText("Nama");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel5.setText("Tempat Lahir");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel6.setText("Tanggal Lahir");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel7.setText("Kode Jabatan");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel9.setText("Jenis Kelamin");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel10.setText("Alamat");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel11.setText("Status");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));
        jPanel1.add(txt_nik, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 360, -1));
        jPanel1.add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 360, -1));
        jPanel1.add(txt_tempatlahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 360, -1));
        jPanel1.add(txt_tanggallahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 360, -1));
        jPanel1.add(txt_jeniskelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 360, -1));
        jPanel1.add(txt_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 360, -1));
        jPanel1.add(txt_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 360, -1));

        jPanel6.setBackground(new java.awt.Color(102, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 810, 40));

        cbo_kd_jabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_kd_jabatanActionPerformed(evt);
            }
        });
        jPanel1.add(cbo_kd_jabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 360, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 870, 320));

        jPanel2.setBackground(new java.awt.Color(51, 255, 255));

        btn_simpan.setIcon(new javax.swing.ImageIcon("D:\\Rima_Cahya_SI 14 D_Netbeens8.0.1\\penggajian\\src\\icon\\SAVE.png")); // NOI18N
        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_ubah.setIcon(new javax.swing.ImageIcon("D:\\Rima_Cahya_SI 14 D_Netbeens8.0.1\\penggajian\\src\\icon\\CANCEL.png")); // NOI18N
        btn_ubah.setText("Ubah");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });

        btn_hapus.setIcon(new javax.swing.ImageIcon("D:\\Rima_Cahya_SI 14 D_Netbeens8.0.1\\penggajian\\src\\icon\\delete.png")); // NOI18N
        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(btn_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(508, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 870, 90));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        tbl_karyawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIK", "Nama", "Tempat Lahir", "Tanggal Lahir", "Jenis Kelamin", "Alamat", "Status", "Kode Jabatan"
            }
        ));
        tbl_karyawan.setToolTipText("");
        tbl_karyawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_karyawanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_karyawan);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 870, 250));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("DATA KARYAWAN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        try
        {
            model_karyawan kry = new model_karyawan();
            kry.setNIK(txt_nik.getText());
            kry.setNama(txt_nama.getText());
            kry.setTempat_lahir(txt_tempatlahir.getText());
            kry.setTgl_lahir(txt_tanggallahir.getText());
            kry.setJenis_kelamin(txt_jeniskelamin.getText());
            kry.setAlamat(txt_alamat.getText());
            kry.setStatus(txt_status.getText());
            kry.setKodeJabatan(cbo_kd_jabatan.getName());
            
            kryservice.ubah(kry);
            JOptionPane.showMessageDialog(this, "Data berhasil diubah!");
            this.refreshdata();
        }
        catch (SQLException e)
        {
            System.out.println("Error fungsi ubah : "+ e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
    try {
            //buat objek mhs dar class modelMhs
            model.model_karyawan kry = new model_karyawan();
            //manipulasi attribut pada modelMhs dari Texfield yang ada di view
            kry.setNIK(txt_nik.getText());
            kry.setNama(txt_nama.getText());
            kry.setTempat_lahir(txt_tempatlahir.getText());
            kry.setTgl_lahir(txt_tanggallahir.getText());
            kry.setJenis_kelamin(txt_jeniskelamin.getText());
            kry.setAlamat(txt_alamat.getText());
            kry.setStatus(txt_status.getText());
            kry.setKodeJabatan(cbo_kd_jabatan.getSelectedItem().toString());
            
            //memanggil perintah tambah
            kryservice.tambah(kry);
            //tampil pesan
            JOptionPane.showMessageDialog(this,"Data berhasil disimpan!");
            //refresh tampilan data
            this.refreshdata();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error fungsi tambah : "+e.toString());
        }
                // TODO add your handling code here:
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        try
        {
            int row = tbl_karyawan.getSelectedRow(); // mendapatkan index dari baris yang di click
            model.model_karyawan kry = new model_karyawan();
            kry.setNIK(tbl_karyawan.getValueAt(row, 0).toString());
            kryservice.hapus(kry);
        
            //tampil pesan
            JOptionPane.showMessageDialog(this,"Data berhasil dihapus!");
            this.refreshdata();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error fungsi tambah : "+e.toString());
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void tbl_karyawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_karyawanMouseClicked
        int row = tbl_karyawan.getSelectedRow(); // mendapatkan index dari baris yang di click
        txt_nik.setText(tbl_karyawan.getValueAt(row, 0).toString());  //menamilkan data pada baris ke row dan column ke 0
        txt_nama.setText(tbl_karyawan.getValueAt(row,1).toString());
        txt_tempatlahir.setText(tbl_karyawan.getValueAt(row,2).toString());
        txt_tanggallahir.setText(tbl_karyawan.getValueAt(row,3).toString());
        txt_jeniskelamin.setText(tbl_karyawan.getValueAt(row,4).toString());
        txt_alamat.setText(tbl_karyawan.getValueAt(row,5).toString());
        txt_status.setText(tbl_karyawan.getValueAt(row,6).toString());
          cbo_kd_jabatan.setName(tbl_karyawan.getValueAt(row,7).toString());
    }//GEN-LAST:event_tbl_karyawanMouseClicked

    private void cbo_kd_jabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_kd_jabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_kd_jabatanActionPerformed

    /**
     * @param args the command line arguments
     */ 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_karyawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JComboBox cbo_kd_jabatan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_karyawan;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_jeniskelamin;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nik;
    private javax.swing.JTextField txt_status;
    private javax.swing.JTextField txt_tanggallahir;
    private javax.swing.JTextField txt_tempatlahir;
    // End of variables declaration//GEN-END:variables
}
